### ISSUE TITLE
SFTP password bug while installation of my_webapp

### ISSUE THREAD

**Issue by MsEleos** [YunoHost-Apps/my_webapp_ynh#28]
```
eleos ~ % sudo yunohost app install my_webapp --debug    
[...]
Available domains:
- eleos.space
- blog.eleos.space
- matrix.eleos.space
Choose a domain for your Webapp (default: eleos.space): blog.eleos.space
Choose a path for your Webapp (default: /site): /
Set the password for the SFTP access. ≥ 5 character: 
Is it a public website? [0 | 1] (default: 1): 
Do you need a MySQL database? [0 | 1] (default: 0): 
22163 ERROR An unexpected error occured
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/app.py", line 768, in app_install
    args=args_list, env=env_dict, user="root")
  File "/usr/lib/moulinette/yunohost/hook.py", line 355, in hook_exec
    command.append(cmd.format(script=cmd_script, args=cmd_args))
ValueError: unmatched '{' in format
```

After changing the sftp password to a new one with only letters and numbers everything worked fine.
It seems there is a problem with symbols password, especially with the character '{' and make the install script crashing.

**Comment by SylvainCecchetto** [comment]
Same problem here

**Comment by AkselRocks** [comment]
Password with  "_" works.

**Comment by tituspijean** [comment]
Users passwords containing `{` or `}` now get rejected.
